# .readthedocs.yaml
# Read the Docs configuration file for Packet Insight
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions if needed:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true
  # Use the default HTML builder
  builder: html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Python configuration - install the package and documentation dependencies
python:
  install:
    # Install documentation-specific requirements
    - requirements: docs/requirements.txt
    # Install the package itself in development mode for autodoc
    - method: pip
      path: .
      extra_requirements:
        - dev
    # Alternative: install just the base package
    # - method: pip
    #   path: .

# Search configuration (optional)
search:
  # Enable search ranking features
  ranking:
    api/: -1  # Lower priority for API docs
    tutorial/: 5  # Higher priority for tutorials